export const categories = [
  "Cooking",
  "Baking",
  "Cocktails",
  "Mixology",
  "Wine Tasting",
  "Drink / Food Pairings",
  "Floral Arrangement",
  "Succulent Arrangement",
  "Cookie Decorating",
  "Cake Decorating",
  "Candle Making",
  "Crafts",
  "Magic",
  "Soap Making",
  "Knitting Classes",
  "Games",
  "Entertaining at Home",
  "Personal Fashion Styling",
  "Makeup",
  "Hair Styling",
  "Classes",
  "Shows",
  "Interactivity",
  "30 min Experiences",
  "45 min Experiences",
  "60 min Experiences",
  "60+ min Experiences",
  "Learning New Skills",
  "Socializing",
  "New Technology",
  "Discovering New Products",
  "Holidays",
  "Themes",
  "Private Experiences",
  "Group Experiences",
  "Meeting New People",
  "Dating",
  "Custom Experiences",
  "Beginner Level",
  "Intermediate Level",
  "Advanced Level",
  "Kits Included",
  "Last Minute Sign Up",
  "Easy Participation",
];

export const selectedCategories = [
  "Cocktails",
  "Mixology",
  "Wine Tasting",
  "Drink / Food Pairings",
  "Floral Arrangement",
];

export const dataArray = [
  {
    name: "Bartender’s Handshake",
    expertName: "Wayne Rigsby",
    expertCategory: "Magician  |  Mixologist",
    expertImage: "https://via.placeholder.com/70",
    duration: "30m",
    guestAllowed: "10 guests",
    price: 100,
    expertImg: "https://via.placeholder.com/24",
    participants: [
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    expertName: "Kimball Cho",
    expertCategory: "Magician  |  Mixologist",
    expertImage: "https://via.placeholder.com/70",
    duration: "30m",
    guestAllowed: "8 guests",
    price: 150,
    expertImg: "https://via.placeholder.com/24",
    participants: [
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    expertName: "Patrick Jane",
    expertCategory: "Magician  |  Mixologist",
    expertImage: "https://via.placeholder.com/70",
    duration: "30m",
    guestAllowed: "7 guests",
    price: 250,
    expertImg: "https://via.placeholder.com/24",
    participants: [
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    expertName: "Teresa Lisbon",
    expertCategory: "Magician  |  Mixologist",
    expertImage: "https://via.placeholder.com/70",
    duration: "30m",
    guestAllowed: "4 guests",
    price: 70,
    expertImg: "https://via.placeholder.com/24",
    participants: [
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    expertName: "Grace Van Pelt",
    expertCategory: "Magician  |  Mixologist",
    expertImage: "https://via.placeholder.com/70",
    duration: "30m",
    guestAllowed: "2 guests",
    price: 40,
    expertImg: "https://via.placeholder.com/24",
    participants: [
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
      { expertImg: "https://via.placeholder.com/24" },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
];

export const greetingMsg = {
  head: "Hey Joe!",
  msg:
    "Check out these experiences we handpicked for you. You can also manage your booked events below.",
};

export const welcomeMsg = {
  head: "Welcome to StayInSocial",
  msg: "Discover and book unique experiences hosted in your home.",
};
