import placeholderImage from "./assets/images/placeholderImage.png";
export const categories = [
  "Cooking",
  "Baking",
  "Cocktails",
  "Mixology",
  "Wine Tasting",
  "Drink / Food Pairings",
  "Floral Arrangement",
  "Succulent Arrangement",
  "Cookie Decorating",
  "Cake Decorating",
  "Candle Making",
  "Crafts",
  "Magic",
  "Soap Making",
  "Knitting Classes",
  "Games",
  "Entertaining at Home",
  "Personal Fashion Styling",
  "Makeup",
  "Hair Styling",
  "Classes",
  "Shows",
  "Interactivity",
  "30 min Experiences",
  "45 min Experiences",
  "60 min Experiences",
  "60+ min Experiences",
  "Learning New Skills",
  "Socializing",
  "New Technology",
  "Discovering New Products",
  "Holidays",
  "Themes",
  "Private Experiences",
  "Group Experiences",
  "Meeting New People",
  "Dating",
  "Custom Experiences",
  "Beginner Level",
  "Intermediate Level",
  "Advanced Level",
  "Kits Included",
  "Last Minute Sign Up",
  "Easy Participation",
];

export const selectedCategories = [
  "Cocktails",
  "Mixology",
  "Wine Tasting",
  "Drink / Food Pairings",
  "Floral Arrangement",
];

export const dataArray = [
  {
    name: "Bartender’s Handshake",
    image:
      "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
    expertName: "Wayne Rigsby",
    expertId: "way-1",
    expertCategory: "Magician  |  Mixologist",
    expertTotalExperience: Math.floor(Math.random() * 10 + 1),
    expertImage: placeholderImage,
    duration: "30m",
    guestAllowed: "10 guests",
    price: 100,
    expertImg: placeholderImage,
    participants: [
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    image:
      "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
    expertName: "Kimball Cho",
    expertId: "kim-4",
    expertCategory: "Magician  |  Mixologist",
    expertTotalExperience: Math.floor(Math.random() * 10 + 1),
    expertImage: placeholderImage,
    duration: "30m",
    guestAllowed: "8 guests",
    price: 150,
    expertImg: placeholderImage,
    participants: [
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    image:
      "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
    expertName: "Patrick Jane",
    expertId: "pat-5",
    expertCategory: "Magician  |  Mixologist",
    expertTotalExperience: Math.floor(Math.random() * 10 + 1),
    expertImage: placeholderImage,
    duration: "30m",
    guestAllowed: "7 guests",
    price: 250,
    expertImg: placeholderImage,
    participants: [
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    image:
      "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
    expertName: "Teresa Lisbon",
    expertId: "ter-2",
    expertCategory: "Magician  |  Mixologist",
    expertTotalExperience: Math.floor(Math.random() * 10 + 1),
    expertImage: placeholderImage,
    duration: "30m",
    guestAllowed: "4 guests",
    price: 70,
    expertImg: placeholderImage,
    participants: [
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
  {
    name: "Bartender’s Handshake",
    image:
      "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
    expertName: "Grace Van Pelt",
    expertId: "gra-3",
    expertCategory: "Magician  |  Mixologist",
    expertTotalExperience: Math.floor(Math.random() * 10 + 1),
    expertImage: placeholderImage,
    duration: "30m",
    guestAllowed: "2 guests",
    price: 40,
    expertImg: placeholderImage,
    participants: [
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
      { expertImg: placeholderImage },
    ],
    participantAccepted: "3/4 people RSVP’d",
  },
];

export const searchedExperiences = [
  {
    Magic: [
      {
        name: "Bartender’s Handshake",
        image:
          "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
        expertName: "Patrick Jane",
        expertId: "pat-5",
        expertCategory: "Magician  |  Mixologist",
        expertTotalExperience: Math.floor(Math.random() * 10 + 1),
        expertImage: placeholderImage,
        duration: "30m",
        guestAllowed: "7 guests",
        price: 250,
        expertImg: placeholderImage,
        participants: [
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
        ],
        participantAccepted: "3/4 people RSVP’d",
      },
      {
        name: "Bartender’s Handshake",
        image:
          "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
        expertName: "Teresa Lisbon",
        expertId: "ter-2",
        expertCategory: "Magician  |  Mixologist",
        expertTotalExperience: Math.floor(Math.random() * 10 + 1),
        expertImage: placeholderImage,
        duration: "30m",
        guestAllowed: "4 guests",
        price: 70,
        expertImg: placeholderImage,
        participants: [
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
        ],
        participantAccepted: "3/4 people RSVP’d",
      },
      {
        name: "Bartender’s Handshake",
        image:
          "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
        expertName: "Grace Van Pelt",
        expertId: "gra-3",
        expertCategory: "Magician  |  Mixologist",
        expertTotalExperience: Math.floor(Math.random() * 10 + 1),
        expertImage: placeholderImage,
        duration: "30m",
        guestAllowed: "2 guests",
        price: 40,
        expertImg: placeholderImage,
        participants: [
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
        ],
        participantAccepted: "3/4 people RSVP’d",
      },
    ],
  },
  {
    Food_Wine: [
      {
        name: "Bartender’s Handshake",
        image:
          "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
        expertName: "Teresa Lisbon",
        expertId: "ter-2",
        expertCategory: "Magician  |  Mixologist",
        expertTotalExperience: Math.floor(Math.random() * 10 + 1),
        expertImage: placeholderImage,
        duration: "30m",
        guestAllowed: "4 guests",
        price: 70,
        expertImg: placeholderImage,
        participants: [
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
        ],
        participantAccepted: "3/4 people RSVP’d",
      },
      {
        name: "Bartender’s Handshake",
        image:
          "https://www.dmarge.com/wp-content/uploads/2020/07/gin-martini-cocktail.jpg",
        expertName: "Grace Van Pelt",
        expertId: "gra-3",
        expertCategory: "Magician  |  Mixologist",
        expertTotalExperience: Math.floor(Math.random() * 10 + 1),
        expertImage: placeholderImage,
        duration: "30m",
        guestAllowed: "2 guests",
        price: 40,
        expertImg: placeholderImage,
        participants: [
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
          { expertImg: placeholderImage },
        ],
        participantAccepted: "3/4 people RSVP’d",
      },
    ],
  },
  {
    Cocktails: [],
  },
];

export const greetingMsg = {
  head: "Hey Joe!",
  msg:
    "Check out these experiences we handpicked for you. You can also manage your booked events below.",
};

export const welcomeMsg = {
  head: "Welcome to StayInSocial",
  msg: "Discover and book unique experiences hosted in your home.",
};

export const expertArray = [
  {
    id: "way-1",
    name: "Wayne Rigsby",
    category: "Magician  |  Mixologist",
    totalExperience: Math.floor(Math.random() * 10 + 1),
    image: placeholderImage,
    description: `"When is Alex going to find a real job?", my aunt said to my mom after I fled NYC for the Vegas strip after college. I graduated with a degree in music, tried what my family referred to as a "real job", and ran away so fast from that life that I didn't have the time to look back...`,
  },
  {
    id: "ter-2",
    name: "Teresa Lisbon",
    category: "Magician  |  Mixologist",
    totalExperience: Math.floor(Math.random() * 10 + 1),
    image: placeholderImage,
    description: `"When is Alex going to find a real job?", my aunt said to my mom after I fled NYC for the Vegas strip after college. I graduated with a degree in music, tried what my family referred to as a "real job", and ran away so fast from that life that I didn't have the time to look back...`,
  },
  {
    id: "gra-3",
    name: "Grace Van Pelt",
    category: "Magician  |  Mixologist",
    totalExperience: Math.floor(Math.random() * 10 + 1),
    image: placeholderImage,
    description: `"When is Alex going to find a real job?", my aunt said to my mom after I fled NYC for the Vegas strip after college. I graduated with a degree in music, tried what my family referred to as a "real job", and ran away so fast from that life that I didn't have the time to look back...`,
  },
  {
    id: "kim-4",
    name: "Kimball Cho",
    category: "Magician  |  Mixologist",
    totalExperience: Math.floor(Math.random() * 10 + 1),
    image: placeholderImage,
    description: `"When is Alex going to find a real job?", my aunt said to my mom after I fled NYC for the Vegas strip after college. I graduated with a degree in music, tried what my family referred to as a "real job", and ran away so fast from that life that I didn't have the time to look back...`,
  },
  {
    id: "pat-5",
    name: "Patrick Jane",
    category: "Magician  |  Mixologist",
    totalExperience: Math.floor(Math.random() * 10 + 1),
    image: placeholderImage,
    description: `"When is Alex going to find a real job?", my aunt said to my mom after I fled NYC for the Vegas strip after college. I graduated with a degree in music, tried what my family referred to as a "real job", and ran away so fast from that life that I didn't have the time to look back...`,
  },
];
